# "Bomb" bulk game importer — feeds a list of popular game names
# through get_board_game_by_name which handles BGG lookup + insertion.

import time
from sqlmodel import Session

from app.services.getBoardGameByName import get_board_game_by_name


SLEEP_BETWEEN_GAMES = 10  # seconds

POPULAR_GAMES = [
    "Catan",
    "Pandemic",
    "Ticket to Ride",
    "Carcassonne",
    "Codenames",
    "Azul",
    "7 Wonders",
    "Dominion",
    "Splendor",
    "Wingspan",
    "Gloomhaven",
    "Terraforming Mars",
    "Scythe",
    "Spirit Island",
    "Root",
    "Brass Birmingham",
    "Agricola",
    "Puerto Rico",
    "Power Grid",
    "Viticulture",
    "Everdell",
    "Clank",
    "Mysterium",
    "Dixit",
    "Betrayal at House on the Hill",
    "King of Tokyo",
    "Small World",
    "Photosynthesis",
    "Patchwork",
    "Jaipur",
    "Star Realms",
    "Sagrada",
    "Santorini",
    "Coup",
    "Love Letter",
    "The Resistance",
    "Sushi Go",
    "Forbidden Island",
    "Forbidden Desert",
    "Pandemic Legacy Season 1",
    "Pandemic Legacy Season 2",
    "Gloomhaven Jaws of the Lion",
    "Ark Nova",
    "Dune Imperium",
    "Cascadia",
    "Calico",
    "Parks",
    "Quacks of Quedlinburg",
    "Villainous",
    "Clue",
    "Monopoly",
    "Risk",
    "Chess",
    "Checkers",
    "Backgammon",
    "Mancala",
    "Uno",
    "Sorry",
    "Life",
    "Stratego",
    "Battleship",
    "Connect Four",
    "Trouble",
    "Yahtzee",
    "Boggle",
    "Scrabble",
    "Trivial Pursuit",
    "Pictionary",
    "Taboo",
    "Cranium",
    "Apples to Apples",
    "Cards Against Humanity",
    "Exploding Kittens",
    "Unstable Unicorns",
    "Munchkin",
    "Settlers of Catan",
    "Cosmic Encounter",
    "Twilight Imperium",
    "Eclipse",
    "Terra Mystica",
    "Gaia Project",
    "Great Western Trail",
    "Concordia",
    "Castles of Burgundy",
    "Orleans",
    "Marco Polo",
    "Caverna",
    "Le Havre",
    "Ora et Labora",
    "Stone Age",
    "Lords of Waterdeep",
    "Champions of Midgard",
    "Raiders of the North Sea",
    "Architects of the West Kingdom",
    "Paladins of the West Kingdom",
    "Viscounts of the West Kingdom",
    "Feast for Odin",
    "Blood Rage",
    "Rising Sun",
    "Ankh",
    "Inis",
    "Kemet",
    "Cyclades",
    "War of the Ring",
    "Star Wars Rebellion",
    "Twilight Struggle",
    "Through the Ages",
    "Brass Lancashire",
    "Food Chain Magnate",
    "Indonesia",
    "Mage Knight",
    "Robinson Crusoe",
    "Dead of Winter",
    "Nemesis",
    "Zombicide",
    "Mansions of Madness",
    "Arkham Horror",
    "Eldritch Horror",
    "Elder Sign",
    "Descent",
    "Imperial Assault",
    "Mice and Mystics",
    "Stuffed Fables",
    "My Little Scythe",
    "Ticket to Ride Europe",
    "Ticket to Ride Nordic Countries",
    "Ticket to Ride Rails and Sails",
    "Memoir 44",
    "Undaunted Normandy",
    "Undaunted North Africa",
    "Unmatched",
    "Funkoverse",
    "Horrified",
    "Jaws",
    "The Crew",
    "The Crew Mission Deep Sea",
    "Hanabi",
    "The Mind",
    "Wavelength",
    "Just One",
    "Decrypto",
    "Mysterium Park",
    "Obscurio",
    "Deception Murder in Hong Kong",
    "Werewolf",
    "Secret Hitler",
    "Avalon",
    "Blood on the Clocktower",
    "One Night Ultimate Werewolf",
    "Sheriff of Nottingham",
    "Bohnanza",
    "Chinatown",
    "Catan Seafarers",
    "Catan Cities and Knights",
    "Catan Traders and Barbarians",
    "Catan Starfarers",
    "Dominion Intrigue",
    "Dominion Seaside",
    "Dominion Prosperity",
    "Thunderstone",
    "Aeons End",
    "Clank In Space",
    "Harry Potter Hogwarts Battle",
    "Marvel Champions",
    "Arkham Horror Card Game",
    "Lord of the Rings Card Game",
    "KeyForge",
    "Magic The Gathering",
    "Netrunner",
    "Race for the Galaxy",
    "Roll for the Galaxy",
    "Res Arcana",
    "Innovation",
    "San Juan",
    "Glory to Rome",
    "Citadels",
    "Mission Red Planet",
    "Libertalia",
    "Ethnos",
    "Alhambra",
    "Tigris and Euphrates",
    "Samurai",
    "Ra",
    "Modern Art",
    "For Sale",
    "No Thanks",
    "Skull",
    "Cockroach Poker",
    "Bluff",
    "Perudo",
    "Camel Up",
    "Flamme Rouge",
    "Jamaica",
    "Tobago",
    "Imhotep",
    "Century Spice Road",
    "Century Golem Edition",
    "Century Eastern Wonders",
    "Gizmos",
    "Space Base",
    "Machi Koro",
    "Valeria Card Kingdoms",
    "Dice Throne",
    "King of New York",
    "Bunny Kingdom",
    "Smallworld Underground",
    "Five Tribes",
    "Quadropolis",
    "Between Two Cities",
    "Between Two Castles",
    "Suburbia",
    "Castles of Mad King Ludwig",
    "Tiny Towns",
    "Tiny Epic Galaxies",
    "Tiny Epic Kingdoms",
    "Tiny Epic Quest",
    "Wingspan European Expansion",
    "Wingspan Oceania Expansion",
    "Wingspan Asia",
    "Maracaibo",
    "Barrage",
    "Kanban EV",
    "Lisboa",
    "The Gallerist",
    "Vinhos",
    "On Mars",
    "Lacerda",
    "Teotihuacan",
    "Tzolkin",
    "Tekhenu",
    "Tawantinsuyu",
    "Trismegistus",
    "Coimbra",
    "Lorenzo il Magnifico",
    "Grand Austria Hotel",
    "Dice Hospital",
    "Circadians First Light",
    "Anachrony",
    "Trickerion",
    "Cerebria",
    "Pendulum",
    "Tapestry",
    "Charterstone",
    "My City",
    "Cleopatra",
    "Lost Ruins of Arnak",
    "Beyond the Sun",
    "Praga Caput Regni",
    "Underwater Cities",
    "Terraforming Mars Ares Expedition",
    "It's a Wonderful World",
    "Hadara",
    "7 Wonders Duel",
    "7 Wonders Architects",
    "Babylon",
    "Luxor",
    "Karnak",
    "Pandemic Iberia",
    "Pandemic Fall of Rome",
    "Pandemic Rising Tide",
    "Pandemic Reign of Cthulhu",
    "Flash Point Fire Rescue",
    "Ghost Stories",
    "Aeons End War Eternal",
    "Legendary Encounters Alien",
    "Sentinels of the Multiverse",
    "Marvel United",
    "Horrified American Monsters",
    "Sleeping Gods",
    "ISS Vanguard",
    "Tainted Grail",
    "Etherfields",
    "Middara",
    "Oathsworn",
    "Frosthaven",
    "Imperial Settlers",
    "51st State",
    "Empires of the Void",
    "Twilight Inscription",
    "Oath",
    "Vast",
    "Leder Games",
    "Pax Pamir",
    "John Company",
    "Wehrlegig",
    "Container",
    "Stockpile",
    "Acquire",
    "Chinatown",
    "Sidereal Confluence",
    "Bora Bora",
    "Bruges",
    "Trajan",
    "Mombasa",
    "Great Western Trail Argentina",
    "Maracaibo",
    "Merv",
    "Marco Polo 2",
    "Russian Railroads",
    "Snowdonia",
    "Age of Steam",
    "Steam",
    "Railways of the World",
    "Ticket to Ride Germany",
    "Ticket to Ride London",
    "Ticket to Ride New York",
    "Ticket to Ride First Journey",
    "Azul Summer Pavilion",
    "Azul Stained Glass",
    "Sagrada Life",
    "Lanterns",
    "Indian Summer",
    "Cottage Garden",
    "Barenpark",
    "New York Zoo",
    "Silver and Gold",
    "Welcome To",
    "Railroad Ink",
    "Cartographers",
    "Rolling Realms",
    "Second Chance",
    "Qwixx",
    "Ganz Schon Clever",
    "Twice as Clever",
    "Clever Cubed",
    "Kingdomino",
    "Queendomino",
    "Isle of Cats",
    "Calico",
    "Cascadia",
    "Verdant",
    "Point Salad",
    "Sushi Go Party",
    "Silver Dagger",
    "Incan Gold",
    "Diamant",
    "Celestia",
    "Deep Sea Adventure",
    "Port Royal",
    "Arboretum",
    "Mandala",
    "Hanamikoji",
    "Targi",
    "Watergate",
    "Raptor",
    "Twilight Inscription",
    "7 Wonders Duel Pantheon",
    "Schotten Totten",
    "Battle Line",
    "Air Land and Sea",
    "Fox in the Forest",
    "The Fox in the Forest Duet",
    "Onitama",
    "Hive",
    "Blokus",
    "Azul Queen Garden",
    "Pandemic Hot Zone",
    "Catan Junior",
    "Ticket to Ride Junior",
    "My First Carcassonne",
    "Rhino Hero",
    "Ice Cool",
    "Zombie Kidz Evolution",
    "Dragomino",
    "MicroMacro Crime City",
    "Detective",
    "Chronicles of Crime",
    "Sherlock Holmes Consulting Detective",
    "Unlock",
    "Exit The Game",
    "Deckscape",
    "Escape Room The Game",
    "Clank Legacy",
    "Aeons End Legacy",
    "Betrayal Legacy",
    "Risk Legacy",
    "SeaFall",
    "Apiary",
    "Earth",
    "Creature Comforts",
    "Brew",
    "Canvas",
    "Chai",
    "Herbaceous",
    "Floriferous",
    "Meadow",
    "Forest Shuffle",
    "Flamecraft",
    "Wyrmspan",
    "Heat Pedal to the Metal",
    "Sky Team",
    "Harmonies",
    "Nucleum",
    "Tiletum",
    "Darwin's Journey",
    "Revive",
    "Lacrimosa",
    "Zhanguo",
    "Messina 1347",
    "Carnegie",
    "Golem",
    "Woodcraft",
    "Obsession",
    "Destinies",
    "Stardew Valley",
    "Minecraft Builders and Biomes",
    "Cthulhu Death May Die",
    "Too Many Bones",
    "Agemonia",
    "Vagrantsong",
    "Final Girl",
    "Marvel Zombies",
    "Descent Legends of the Dark",
    "Journeys in Middle Earth",
    "Star Wars Outer Rim",
    "Star Wars X Wing",
    "Warhammer Underworlds",
    "Undaunted Stalingrad",
    "Commands and Colors",
    "Paths of Glory",
    "Sekigahara",
    "Waterloo",
    "Agricola Revised Edition",
    "Caverna Cave vs Cave",
    "Nusfjord",
    "Hallertau",
    "Fields of Arle",
    "Glass Road",
    "At the Gates of Loyang",
    "Ora et Labora",
    "Bonfire",
    "Merlin",
    "Rajas of the Ganges",
    "Heaven and Ale",
    "Santa Maria",
    "Ginkgopolis",
    "Troyes",
    "Tournay",
    "The Manhattan Project",
    "Viticulture Tuscany",
    "Scythe Rise of Fenris",
    "Root Riverfolk",
    "Root Underworld",
    "Nemesis Lockdown",
    "Eclipse Second Dawn",
    "Dune",
    "Dune Imperium Uprising",
    "Arcs",
    "Kabuto Sumo",
    "Klask",
    "Crokinole",
    "Bullet",
    "Kites",
    "Regicide",
    "The Search for Planet X",
    "Cryptid",
    "So Clover",
    "Pictures",
    "Telestrations",
    "Wits and Wagers",
    "Concept",
    "Monikers",
    "Time Stories",
    "Pandemic Rapid Response",
]


def bomb_board_games(session: Session) -> int:
    """Look up each popular game by name, adding any that aren't
    already in the DB. Returns the number of games added."""
    added = 0

    for i, name in enumerate(POPULAR_GAMES, 1):
        print(f"[bomb] {i}/{len(POPULAR_GAMES)} — looking up '{name}'")

        try:
            results = get_board_game_by_name(name, session)
            if results:
                added += 1
                print(f"[bomb]   found/added '{name}'")
        except Exception as e:
            print(f"[bomb]   skipped '{name}': {e}")

        time.sleep(SLEEP_BETWEEN_GAMES)

    print(f"[bomb] finished — {added} games processed")
    return added
